using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging")]
[assembly: SuppressMessage("Style", "IDE0008:Use explicit type")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization")]
[assembly: SuppressMessage("Style", "IDE0042:Deconstruct variable declaration")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used")]
[assembly: SuppressMessage("Style", "IDE0130:Namespace does not match folder structure")]
[assembly: SuppressMessage("Style", "IDE0305:Simplify collection initialization")]
[assembly: SuppressMessage("Style", "IDE0160:Convert to block scoped namespace")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal")]
[assembly: SuppressMessage("Style", "IDE0022:Use block body for method")]
[assembly: SuppressMessage("Performance", "CA1819:Properties should not return arrays")]
[assembly: SuppressMessage("Design", "CA1040:Avoid empty interfaces")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only")]
[assembly: SuppressMessage("Security", "CA5394:Do not use insecure randomness")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase")]
[assembly: SuppressMessage("Performance", "CA1848:Use the LoggerMessage delegates")]
[assembly: SuppressMessage("Design", "CA1056:URI-like properties should not be strings")]
[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists")]
[assembly: SuppressMessage("Naming", "CA1724:Type names should not match namespaces")]
