using Microsoft.AspNetCore.Antiforgery;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Globalization;

namespace CurriculumPortal;

[Authorize(Roles = Roles.Teacher)]
public class CourseEvaluationModel(CourseService courseService, ConfigService config, AppOptions options, IAntiforgery antiforgery) : PageModel
{
  public string CourseId { get; private set; } = string.Empty;
  public CourseEntity Course { get; private set; }
  public CourseEvaluation Evaluation { get; private set; }
  public IReadOnlyList<UnitEntity> Units { get; private set; } = [];
  public string CsrfToken { get; private set; } = string.Empty;
  public bool IsAdmin { get; private set; }
  public bool IsOverviewStale { get; private set; }
  private HashSet<string> StaleUnitIds { get; } = new(StringComparer.Ordinal);

  public string GetModelName(string model) => string.IsNullOrWhiteSpace(model) ? "gpt-5.6-sol" : model;

  public string GetGenerationText(string model, DateTimeOffset generatedAt) => generatedAt == default
    ? $"Generated by {GetModelName(model)}"
    : $"Generated by {GetModelName(model)} on {generatedAt.UtcDateTime.ToString("d MMMM yyyy", CultureInfo.CurrentCulture)}";

  public bool IsUnitStale(string unitId) => !string.IsNullOrWhiteSpace(unitId) && StaleUnitIds.Contains(unitId);

  public async Task<IActionResult> OnGetAsync(string courseId)
  {
    if (string.IsNullOrWhiteSpace(courseId))
    {
      return BadRequest("Course ID is required.");
    }

    var course = await courseService.TryGetCourseAsync(courseId);
    if (course is null)
    {
      return NotFound("Course not found.");
    }

    if (!User.CanEditCourse(course, config))
    {
      return Forbid();
    }

    CourseId = courseId;
    Course = course;
    Evaluation = await courseService.TryGetCourseEvaluationAsync(courseId);
    Units = Evaluation is null ? [] : await courseService.ListUnitsAsync(courseId);
    if (Evaluation is not null)
    {
      Evaluation.Units ??= [];
      var currentUnitsById = Units.ToDictionary(o => o.RowKey, StringComparer.Ordinal);
      var evaluatedUnits = Evaluation.Units.Select((evaluation, index) =>
      {
        var unitId = string.IsNullOrWhiteSpace(evaluation.UnitId) ? Units.ElementAtOrDefault(index)?.RowKey : evaluation.UnitId;
        return (Evaluation: evaluation, UnitId: unitId, Current: unitId is null ? null : currentUnitsById.GetValueOrDefault(unitId));
      }).ToList();

      var legacyUnitIds = new HashSet<string>(StringComparer.Ordinal);
      if (!Evaluation.Overall.EvaluationSourceUpdatedAt.HasValue)
        legacyUnitIds.UnionWith(Units.Select(o => o.RowKey));
      legacyUnitIds.UnionWith(evaluatedUnits
        .Where(o => !o.Evaluation.EvaluationSourceUpdatedAt.HasValue && o.Current is not null)
        .Select(o => o.UnitId));

      var lastModifiedTasks = legacyUnitIds.ToDictionary(
        o => o,
        o => courseService.GetEvaluationContentLastModifiedAsync(o, HttpContext.RequestAborted),
        StringComparer.Ordinal);
      await Task.WhenAll(lastModifiedTasks.Values);
      var legacyContentUpdatedAt = lastModifiedTasks.ToDictionary(o => o.Key, o => o.Value.Result, StringComparer.Ordinal);

      var currentUnitIds = Units.Select(o => o.RowKey).ToList();
      var overviewSourceUnitIds = Evaluation.Overall.SourceUnitIds
        ?? Evaluation.Units.Select(o => o.UnitId).Where(o => !string.IsNullOrWhiteSpace(o)).ToList();
      var overviewRosterChanged = (Evaluation.Overall.SourceUnitIds is not null || overviewSourceUnitIds.Count > 0)
        && !overviewSourceUnitIds.SequenceEqual(currentUnitIds, StringComparer.Ordinal);
      IsOverviewStale = !string.Equals(GetModelName(Evaluation.Overall.Model), options.OpenAIModel, StringComparison.Ordinal);
      if (Evaluation.Overall.EvaluationSourceUpdatedAt.HasValue)
      {
        var currentSourceUpdatedAt = Units.Select(o => o.Timestamp ?? DateTimeOffset.MinValue)
          .Append(Course.Timestamp ?? DateTimeOffset.MinValue)
          .Max();
        IsOverviewStale |= currentSourceUpdatedAt > Evaluation.Overall.EvaluationSourceUpdatedAt.Value || overviewRosterChanged;
      }
      else if (Evaluation.Overall.GeneratedAt != default)
      {
        IsOverviewStale |= Course.Timestamp > Evaluation.Overall.GeneratedAt
          || Units.Any(o => o.Timestamp > Evaluation.Overall.GeneratedAt)
          || legacyContentUpdatedAt.Values.Any(o => o > Evaluation.Overall.GeneratedAt)
          || overviewRosterChanged;
      }

      foreach (var item in evaluatedUnits.Where(o => o.Current is not null))
      {
        var isStale = !string.Equals(GetModelName(item.Evaluation.Model), options.OpenAIModel, StringComparison.Ordinal)
          || (item.Evaluation.EvaluationSourceUpdatedAt.HasValue
            ? item.Current.Timestamp.GetValueOrDefault() > item.Evaluation.EvaluationSourceUpdatedAt.Value
            : item.Evaluation.GeneratedAt != default
              && (item.Current.Timestamp > item.Evaluation.GeneratedAt
                || legacyContentUpdatedAt.GetValueOrDefault(item.UnitId) > item.Evaluation.GeneratedAt));
        if (isStale)
          StaleUnitIds.Add(item.UnitId);
      }
    }
    CsrfToken = antiforgery.GetAndStoreTokens(HttpContext).RequestToken ?? string.Empty;
    IsAdmin = User.IsInRole(Roles.Admin);

    return Page();
  }
}
