using System.Globalization;

namespace CurriculumPortal;

public sealed class CourseEvaluationReport
{
  public string CourseId { get; init; } = string.Empty;
  public CourseEntity Course { get; init; }
  public CourseEvaluation Evaluation { get; init; }
  public IReadOnlyList<UnitEntity> Units { get; init; } = [];
  public bool ShowBackButton { get; init; }
  public bool ShowControls { get; init; }
  public bool ShowGenerationDetails { get; init; }
  public bool CanEvaluateCourse { get; init; }
  public bool IsOverviewStale { get; init; }
  public int MaximumPriority { get; init; } = 4;
  public IReadOnlySet<string> StaleUnitIds { get; init; } = new HashSet<string>(StringComparer.Ordinal);

  public string GetGenerationText(string model, DateTimeOffset generatedAt) => generatedAt == default
    ? $"Generated by {CourseEvaluationService.GetModelName(model)}"
    : $"Generated by {CourseEvaluationService.GetModelName(model)} on {generatedAt.UtcDateTime.ToString("d MMMM yyyy", CultureInfo.CurrentCulture)}";

  public bool IsUnitStale(string unitId) => !string.IsNullOrWhiteSpace(unitId) && StaleUnitIds.Contains(unitId);
}
